create schema nova_auction;
use nova_auction;

create table user_info(
id int PRIMARY key AUTO_INCREMENT,
first_name varchar(25),
last_name varchar(25),
email varchar(50),
pass varchar(50),
phonenumber varchar(20)
);

create table city(
id int PRIMARY key AUTO_INCREMENT,
city_name varchar(20)
);

create table car_info_makes(
id int PRIMARY key AUTO_INCREMENT,
makes_name varchar(20)
);

create table car_info_model(
id int PRIMARY key AUTO_INCREMENT,
makes_id int,
model_name varchar(20),
FOREIGN KEY (makes_id) REFERENCES car_info_makes(id)
);


create table car_info(
id int PRIMARY key AUTO_INCREMENT,
year_of_make date,
user_id int,
model int,
city int,
price int,
img MEDIUMBLOB,
FOREIGN KEY (user_id) REFERENCES user_info(id),
FOREIGN KEY (model) REFERENCES car_info_model(id),
FOREIGN KEY (city) REFERENCES city(id)
);

insert into car_info_makes values
    (default,'Abarth'),
    (default,'AC'),
    (default,'Acura'),
    (default,'Aixam'),
    (default,'Alfa Romeo'),
    (default,'Ariel'),
    (default,'Arrinera'),
    (default,'Aston Martin'),
    (default,'Audi'),
    (default,'Bentley'),
    (default,'BMW'),
    (default,'Bugatti'),
    (default,'Buick'),
    (default,'Cadillac'),
    (default,'Caterham'),
    (default,'Chevrolet'),
    (default,'Chrysler'),
    (default,'Citroën'),
    (default,'Corvette'),
    (default,'Dacia'),
    (default,'Daf'),
    (default,'Daihatsu'),
    (default,'Dodge'),
    (default,'DR Motor'),
    (default,'Elfin'),
    (default,'Ferrari'),
    (default,'Fiat'),
    (default,'Ford'),
    (default,'Gaz'),
    (default,'Geely'),
    (default,'Gillet'),
    (default,'Ginetta'),
    (default,'General Motors'),
    (default,'GMC'),
    (default,'Great Wall'),
    (default,'Gumpert'),
    (default,'Hennessey logo'),
    (default,'Holden'),
    (default,'Honda'),
    (default,'Hummer'),
    (default,'Hyundai'),
    (default,'Infiniti'),
    (default,'Isuzu'),
    (default,'Jaguar'),
    (default,'Jeep'),
    (default,'Joss'),
    (default,'Kia'),
    (default,'Koenigsegg'),
    (default,'Lada'),
    (default,'Lamborghini'),
    (default,'Lancia'),
    (default,'Land Rover'),
    (default,'Lexus'),
    (default,'Lincoln'),
    (default,'Lotus'),
    (default,'Luxgen'),
    (default,'Mahindra'),
    (default,'Maruti Suzuki'),
    (default,'Maserati'),
    (default,'Maybach'),
    (default,'Mazda'),
    (default,'Mclaren'),
    (default,'Mercedes'),
    (default,'MG'),
    (default,'Mini'),
    (default,'Mitsubishi'),
    (default,'Morgan Motor'),
    (default,'Mustang logo'),
    (default,'Nissan'),
    (default,'Noble'),
    (default,'Opel'),
    (default,'Pagani'),
    (default,'Panoz'),
    (default,'Perodua'),
    (default,'Peugeot'),
    (default,'Piaggio'),
    (default,'Pininfarina'),
    (default,'Porsche'),
    (default,'Proton'),
    (default,'Renault'),
    (default,'Reva'),
    (default,'Rimac'),
    (default,'Rolls Royce'),
    (default,'Ruf logo'),
    (default,'Saab'),
    (default,'Scania'),
    (default,'Scion'),
    (default,'Seat'),
    (default,'Shelby'),
    (default,'Skoda'),
    (default,'Smart'),
    (default,'Spyker'),
    (default,'Ssangyong'),
    (default,'SSC'),
    (default,'Subaru'),
    (default,'Suzuki'),
    (default,'Tata'),
    (default,'Tatra'),
    (default,'Tesla'),
    (default,'Toyota'),
    (default,'Tramontana'),
    (default,'Troller'),
    (default,'TVR'),
    (default,'UAZ'),
    (default,'Vandenbrink'),
    (default,'Vauxhall'),
    (default,'Vector Motors'),
    (default,'Venturi'),
    (default,'Volkswagen'),
    (default,'Volvo'),
    (default,'Wiesmann'),
    (default,'Zagato'),
    (default,'Zaz'),
    (default,'Zil');

 insert into car_info_model values
 Column1
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'A-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A4 allroad'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A6 allroad'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'A8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Acadia'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Accent'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Accord'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Accord Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lucid')),'Air'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Altima'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Ariya'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Armada'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Arteon'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Ascent'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Atlas'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Atlas Cross Sport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Avalon'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Avalon Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lamborghini')),'Aventador'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lincoln')),'Aviator'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Bentley')),'Bentayga'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Blazer'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Blazer EV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Bolt EUV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Bolt EV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Bronco'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Bronco Sport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'BRZ'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'bZ4X'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'C-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'C-HR'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'C40 Recharge'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Camaro'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Camry'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Camry Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Canyon Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Canyon Extended Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Carnival'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'Cayenne'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'Cayenne Coupe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'Celestiq'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Dodge')),'Challenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Dodge')),'Charger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Cherokee'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Civic'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Civic Type R'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'CLA'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Clarity Fuel Cell'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Clarity Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'CLS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MINI')),'Clubman'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Colorado Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Colorado Extended Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Compass'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Bentley')),'Continental GT'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MINI')),'Convertible'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Corolla'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Corolla Cross'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Corolla Cross Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Corolla Hatchback'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Corolla Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lincoln')),'Corsair'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Corvette'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MINI')),'Countryman'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'CR-V'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'CR-V Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Crosstrek'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Crown'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'CT4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'CT5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rolls-Royce')),'Cullinan'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-30'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-50'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-70'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-9'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'CX-90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Tesla')),'Cybertruck'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rolls-Royce')),'Dawn'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Aston Martin')),'DB11'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Aston Martin')),'DBS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Aston Martin')),'DBX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Defender 110'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Defender 130'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Defender 90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Discovery'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Discovery Sport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Dodge')),'Durango'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'E-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jaguar')),'E-PACE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'E-Transit 350 Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'e-tron'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'e-tron GT'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'e-tron S'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'e-tron S Sportback'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'e-tron Sportback'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mitsubishi')),'Eclipse Cross'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'EcoSport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Edge'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Elantra'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Elantra Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Elantra N'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'Electrified G80'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'Electrified GV70'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Buick')),'Enclave'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Buick')),'Encore'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Buick')),'Encore GX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Buick')),'Envision'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Equinox'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Equinox EV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'ES'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'Escalade'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'Escalade ESV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Escape'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Escape Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'EV6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'EV9'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lotus')),'Evora GT'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'EX90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Expedition'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Expedition MAX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Explorer'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Express 2500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Express 2500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Express 3500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Express 3500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jaguar')),'F-PACE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jaguar')),'F-TYPE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F150 Lightning'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F150 Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F150 Super Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F150 SuperCrew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F250 Super Duty Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F250 Super Duty Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F250 Super Duty Super Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F350 Super Duty Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F350 Super Duty Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F350 Super Duty Super Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F450 Super Duty Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'F450 Super Duty Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'F8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Bentley')),'Flying Spur'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Forester'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Forte'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Frontier Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Frontier King Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'G-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'G70'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'G80'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'G90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Maserati')),'Ghibli'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rolls-Royce')),'Ghost'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Alfa Romeo')),'Giulia'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'GLA'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Gladiator'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'GLB'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'GLC'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'GLC Coupe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'GLE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'GLS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Golf GTI'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Golf R'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'GR Corolla'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'GR Supra'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'GR86'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Grand Cherokee'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Grand Cherokee 4xe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Grand Cherokee L'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Grand Highlander'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Grand Wagoneer'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Grand Wagoneer L'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Maserati')),'Grecale'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'GT-R'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'GV60'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'GV70'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Genesis')),'GV80'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'GX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MINI')),'Hardtop 2 Door'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MINI')),'Hardtop 4 Door'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Highlander'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Highlander Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Dodge')),'Hornet'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'HR-V'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Hummer EV Pickup'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Hummer EV SUV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lamborghini')),'Huracan'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jaguar')),'I-PACE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'i3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'i4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'i7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'ID.4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'ID.Buzz'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Acura')),'ILX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Impreza'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Insight'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Acura')),'Integra'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'IONIQ 5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'IONIQ 6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'IONIQ 7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Ioniq Electric'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Ioniq Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Ioniq Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'IS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'iX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Jetta'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Jetta GLI'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'K5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Kicks'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Kona'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Kona Electric'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Kona N'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Land Cruiser'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'LC'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'LEAF'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Legacy'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Maserati')),'Levante'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'LS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'LX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'LYRIQ'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'M2'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'M3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'M4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'M5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'M8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'Macan'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Malibu'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Maverick'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Maxima'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'MAZDA3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'MAZDA6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Maserati')),'MC20'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Acura')),'MDX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG A-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG C-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG CLA'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG CLS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG E-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG EQS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG G-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLA'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLB'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLC'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLC Coupe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLE Coupe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GLS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG GT'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG S-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-AMG SL'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-EQ EQB'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-EQ EQE'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-EQ EQE SUV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-EQ EQS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-EQ EQS SUV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-Maybach GLS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Mercedes-Maybach S-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Metris Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Metris Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mitsubishi')),'Mirage'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mitsubishi')),'Mirage G4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Mirai'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Tesla')),'Model 3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Tesla')),'Model S'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Tesla')),'Model X'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Tesla')),'Model Y'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Murano'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Mustang'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Mustang MACH-E'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'MX-30'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'MX-5 Miata'),
(default,(select id from car_info_makes where lower(makes_name) = lower('MAZDA')),'MX-5 Miata RF'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lincoln')),'Nautilus'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lincoln')),'Navigator'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lincoln')),'Navigator L'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'NEXO'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Niro'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Niro EV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Niro Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Acura')),'NSX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'NV1500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'NV200'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'NV2500 HD Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'NV3500 HD Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'NV3500 HD Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'NX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Fisker')),'Ocean'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Odyssey'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Outback'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mitsubishi')),'Outlander'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mitsubishi')),'Outlander PHEV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mitsubishi')),'Outlander Sport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chrysler')),'Pacifica'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chrysler')),'Pacifica Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Palisade'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'Panamera'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Passat'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Passport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Pathfinder'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rolls-Royce')),'Phantom'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Pilot'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'Portofino'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Prius'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Prius Prime'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Prologue'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'ProMaster Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'ProMaster City'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'ProMaster Window Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q4 e-tron'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q4 Sportback e-tron'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q5 Sportback'),
(default,(select id from car_info_makes where lower(makes_name) = lower('INFINITI')),'Q50'),
(default,(select id from car_info_makes where lower(makes_name) = lower('INFINITI')),'Q60'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'Q8 e-tron'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Maserati')),'Quattroporte'),
(default,(select id from car_info_makes where lower(makes_name) = lower('INFINITI')),'QX50'),
(default,(select id from car_info_makes where lower(makes_name) = lower('INFINITI')),'QX55'),
(default,(select id from car_info_makes where lower(makes_name) = lower('INFINITI')),'QX60'),
(default,(select id from car_info_makes where lower(makes_name) = lower('INFINITI')),'QX80'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rivian')),'R1S'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rivian')),'R1T'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'R8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Range Rover'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Range Rover Evoque'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Range Rover Sport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Land Rover')),'Range Rover Velar'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Ranger SuperCab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Ranger SuperCrew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'RAV4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'RAV4 Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'RAV4 Prime'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'RC'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Acura')),'RDX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Recon'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Renegade'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Honda')),'Ridgeline'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Rio'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Rogue'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Rogue Sport'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'Roma'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'RS 3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'RS 5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'RS 6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'RS 7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'RS e-tron GT'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'RS Q8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'RX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'RZ'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'S-Class'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'S3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'S4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'S5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'S6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'S60'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'S7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'S8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'S90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Santa Cruz'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Santa Fe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Santa Fe Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Santa Fe Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Savana 2500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Savana 2500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Savana 3500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Savana 3500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sedona'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Seltos'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Sentra'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Sequoia'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'SF90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Sienna'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 1500 Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 1500 Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 1500 Limited Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 1500 Limited Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 1500 Limited Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 1500 Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 2500 HD Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 2500 HD Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 2500 HD Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 3500 HD Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 3500 HD Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra 3500 HD Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Sierra EV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 1500 Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 1500 Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 1500 Limited Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 1500 Limited Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 1500 Limited Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 1500 Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 2500 HD Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 2500 HD Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 2500 HD Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 3500 HD Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 3500 HD Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado 3500 HD Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Silverado EV'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'Solterra'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Sonata'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Sonata Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sorento'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sorento Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sorento Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Soul'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Spark'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sportage'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sportage Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Sportage Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 1500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 1500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 1500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 1500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 2500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 2500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 2500 Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 2500 Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 2500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 2500 Passenger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 3500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 3500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 3500 Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 3500 Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 3500 XD Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 3500 XD Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 3500 XD Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 3500XD Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 4500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 4500 Cargo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Freightliner')),'Sprinter 4500 Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Mercedes')),'Sprinter 4500 Crew'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'SQ5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'SQ5 Sportback'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'SQ7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'SQ8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Alfa Romeo')),'Stelvio'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Stinger'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Suburban'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Tacoma Access Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Tacoma Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Tahoe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Taos'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'Taycan'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'Taycan Cross Turismo'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Kia')),'Telluride'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Terrain'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volkswagen')),'Tiguan'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Titan Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Titan King Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'TITAN XD Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Acura')),'TLX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Alfa Romeo')),'Tonale'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Trailblazer'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 150 Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 150 Crew Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 150 Passenger Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 250 Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 250 Crew Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 350 Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 350 Crew Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 350 HD Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 350 HD Crew Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit 350 Passenger Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit Connect Cargo Van'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ford')),'Transit Connect Passenger Wagon'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Traverse'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chevrolet')),'Trax'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Audi')),'TT'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Tucson'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Tucson Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Tucson Plug-in Hybrid'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Tundra CrewMax'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Tundra Double Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Tundra Hybrid CrewMax'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'TX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lamborghini')),'Urus'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Lexus')),'UX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'V60'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'V90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Aston Martin')),'Vantage'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Veloster'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Hyundai')),'Venue'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'Venza'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Versa'),
(default,(select id from car_info_makes where lower(makes_name) = lower('VinFast')),'VF 6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('VinFast')),'VF 7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('VinFast')),'VF 8'),
(default,(select id from car_info_makes where lower(makes_name) = lower('VinFast')),'VF 9'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Wagoneer'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Wagoneer L'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Rolls-Royce')),'Wraith'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Wrangler'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Wrangler 4xe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Wrangler Unlimited'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jeep')),'Wrangler Unlimited 4xe'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Subaru')),'WRX'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X1'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X2'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X3 M'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X4 M'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X5 M'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X6 M'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'X7'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'XC40'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'XC40 Recharge'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'XC60'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Volvo')),'XC90'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Jaguar')),'XF'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'XM'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'XT4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'XT5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Cadillac')),'XT6'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Yukon'),
(default,(select id from car_info_makes where lower(makes_name) = lower('GMC')),'Yukon XL'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Nissan')),'Z'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'Z4'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Polestar')),'1'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'1500 Classic Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'1500 Classic Quad Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'1500 Classic Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'1500 Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'1500 Quad Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Polestar')),'2'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'2 Series'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'2500 Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'2500 Mega Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'2500 Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'296 GTB'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Polestar')),'3'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'3 Series'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Chrysler')),'300'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'3500 Crew Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'3500 Mega Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ram')),'3500 Regular Cab'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'4 Series'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'488 Pista'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'4Runner'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Polestar')),'5'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'5 Series'),
(default,(select id from car_info_makes where lower(makes_name) = lower('FIAT')),'500X'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'7 Series'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'718 Boxster'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'718 Cayman'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'718 Spyder'),
(default,(select id from car_info_makes where lower(makes_name) = lower('BMW')),'8 Series'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'812 Competizione'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'812 Competizione A'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'812 GTS'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Ferrari')),'812 Superfast'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Toyota')),'86'),
(default,(select id from car_info_makes where lower(makes_name) = lower('Porsche')),'911'),

    /* (default,(select id from car_info_makes where lower(makes_name) = 'toyota'),'avalon'),
    (default,(select id from car_info_makes where lower(makes_name) = 'toyota'),'camry'),
    (default,(select id from car_info_makes where lower(makes_name) = 'toyota'),'corolla'),
    (default,(select id from car_info_makes where lower(makes_name) = 'tesla'),'s'),
    (default,(select id from car_info_makes where lower(makes_name) = 'tesla'),'3'),
    (default,(select id from car_info_makes where lower(makes_name) = 'tesla'),'x'),
    (default,(select id from car_info_makes where lower(makes_name) = 'tesla'),'y'),
    (default,(select id from car_info_makes where lower(makes_name) = 'hyundai'),'sonata'),
    (default,(select id from car_info_makes where lower(makes_name) = 'hyundai'),'accent'),
    (default,(select id from car_info_makes where lower(makes_name) = 'nissan'),'gtr'),
    (default,(select id from car_info_makes where lower(makes_name) = 'nissan'),'patrol'),
    (default,(select id from car_info_makes where lower(makes_name) = 'nissan'),'sunny'),
    (default,(select id from car_info_makes where lower(makes_name) = 'mercedes'),'g'),
    (default,(select id from car_info_makes where lower(makes_name) = 'ford'),'fusion');  */

insert into city values
    (default,'ajloun'),
    (default,'amman'),
    (default,'aqaba'),
    (default,'balqa'),
    (default,'irbid'),
    (default,'jerash'),
    (default,'karak'),
    (default,'maan'),
    (default,'madaba'),
    (default,'mafraq'),
    (default,'tafilah'),
    (default,'zarqa');
